services:
  db:
    image: pgvector/pgvector:pg17  # pgvector가 사전 설치된 공식 이미지
    container_name: cleanview-db
    restart: always
    environment:
      POSTGRES_USER: cleanuser
      POSTGRES_PASSWORD: cleanpassword
      POSTGRES_DB: cleanviewai
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # 데이터 휘발 방지