"""add_user_id_to_document_chunks

Revision ID: d2ab9cb93830
Revises: 8a70f2cb9646
Create Date: 2026-05-24 19:09:48.490477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2ab9cb93830'
down_revision: Union[str, Sequence[str], None] = '8a70f2cb9646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. 일단 user_id를 NULL 허용으로 추가
    op.add_column('document_chunks', sa.Column('user_id', sa.String(length=100), nullable=True))
    
    # 2. 기존 데이터에 임시 user_id 부여 (기존 데이터가 날아가지 않게 함)
    op.execute("UPDATE document_chunks SET user_id = 'default_user' WHERE user_id IS NULL")
    
    # 3. 이제 필수 값으로 변경
    op.alter_column('document_chunks', 'user_id', nullable=False)
    
    # 4. session_id 타입 변경 (VARCHAR -> BigInteger)
    # 기존 데이터가 숫자 형태의 문자열(예: '123')이라면 PostgreSQL이 자동 변환해 줍니다.
    op.alter_column('document_chunks', 'session_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using='session_id::bigint') # 💡 이게 핵심입니다!
               
    op.create_index(op.f('ix_document_chunks_user_id'), 'document_chunks', ['user_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_user_id'), table_name='document_chunks')
    op.alter_column('document_chunks', 'session_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('document_chunks', 'user_id')
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('trace_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###
